# Default solver configuration
abstraction_config:
  abstractor_type: "dynamic"
  model_key: "your-model-key"
  include_train_input: true
  include_test_input: true
  include_image: true

program_gen_config:
  model_key: "your-model-key"
  include_train_input: true
  include_test_input: true
  include_abstraction: false
  include_image: false

executor_config:
  model_key: "your-model-key"
  include_train_input: true
  include_test_input: true
  include_nl_program: true
  include_abstraction: false
  test_train_accuracy: false  # If true, also generate outputs for training examples
